import logging
import os
from typing import Optional

from jira import JIRA
from jira.exceptions import JIRAError
from dotenv import load_dotenv

from app.models import UserStory, TestCase, ReleaseNote, RequestType

load_dotenv()
logger = logging.getLogger(__name__)


class JiraIntegration:
    """Handles all Jira operations: creating issues, attaching test cases, comments."""

    def __init__(self):
        self.url = os.getenv("JIRA_URL", "")
        self.user = os.getenv("JIRA_USER_EMAIL", "")
        self.token = os.getenv("JIRA_API_TOKEN", "")
        self.project_key = os.getenv("JIRA_PROJECT_KEY", "PROJ")
        self.story_type = os.getenv("JIRA_DEFAULT_ISSUE_TYPE", "Story")
        self.bug_type = os.getenv("JIRA_BUG_ISSUE_TYPE", "Bug")
        self._client: Optional[JIRA] = None

    @property
    def is_configured(self) -> bool:
        return bool(self.url and self.user and self.token)

    @property
    def client(self) -> JIRA:
        if self._client is None:
            if not self.is_configured:
                raise RuntimeError(
                    "Jira is not configured. Set JIRA_URL, JIRA_USER_EMAIL, "
                    "and JIRA_API_TOKEN in your .env file."
                )
            self._client = JIRA(
                server=self.url,
                basic_auth=(self.user, self.token),
            )
        return self._client

    def _map_issue_type(self, story: UserStory) -> str:
        if story.request_type == RequestType.BUG_FIX:
            return self.bug_type
        return self.story_type

    def _map_priority(self, story: UserStory) -> Optional[str]:
        priority_map = {
            "critical": "Highest",
            "high": "High",
            "medium": "Medium",
            "low": "Low",
        }
        if story.priority:
            return priority_map.get(story.priority.value)
        return None

    def _build_description(self, story: UserStory) -> str:
        """Build rich Jira description from user story using Jira wiki markup."""
        parts = []

        # User story format
        if story.as_a or story.i_want or story.so_that:
            parts.append("h2. User Story")
            if story.as_a:
                parts.append(f"*As a* {story.as_a}")
            if story.i_want:
                parts.append(f"*I want* {story.i_want}")
            if story.so_that:
                parts.append(f"*So that* {story.so_that}")
            parts.append("")

        # Description
        if story.description:
            parts.append("h2. Description")
            parts.append(story.description)
            parts.append("")

        # Acceptance Criteria
        if story.acceptance_criteria:
            parts.append("h2. Acceptance Criteria")
            for ac in story.acceptance_criteria:
                parts.append(f"* {ac}")
            parts.append("")

        # Bug-specific fields
        if story.request_type == RequestType.BUG_FIX:
            if story.steps_to_reproduce:
                parts.append("h2. Steps to Reproduce")
                for i, step in enumerate(story.steps_to_reproduce, 1):
                    parts.append(f"# {step}")
                parts.append("")

            if story.expected_behavior:
                parts.append("h2. Expected Behavior")
                parts.append(story.expected_behavior)
                parts.append("")

            if story.actual_behavior:
                parts.append("h2. Actual Behavior")
                parts.append(story.actual_behavior)
                parts.append("")

        # Metadata
        if story.affected_module:
            parts.append(f"*Affected Module:* {story.affected_module}")
        if story.estimated_effort:
            parts.append(f"*Estimated Effort:* {story.estimated_effort}")

        # Tags
        if story.tags:
            parts.append(f"\n*Tags:* {', '.join(story.tags)}")

        parts.append("\n----")
        parts.append("_Generated by AI-Orchestrated Release & Enhancement Tool_")

        return "\n".join(parts)

    async def create_issue(self, story: UserStory) -> dict:
        """Create a Jira issue from a user story. Returns issue key and URL."""
        issue_type = self._map_issue_type(story)
        description = self._build_description(story)

        fields = {
            "project": {"key": self.project_key},
            "summary": story.title or "Untitled User Story",
            "description": description,
            "issuetype": {"name": issue_type},
        }

        priority = self._map_priority(story)
        if priority:
            fields["priority"] = {"name": priority}

        if story.tags:
            fields["labels"] = [tag.replace(" ", "-") for tag in story.tags]

        try:
            issue = self.client.create_issue(fields=fields)
            logger.info(f"Created Jira issue: {issue.key}")
            return {
                "key": issue.key,
                "id": issue.id,
                "url": f"{self.url}/browse/{issue.key}",
                "summary": story.title,
            }
        except JIRAError as e:
            logger.error(f"Jira create issue error: {e.text}")
            raise RuntimeError(f"Failed to create Jira issue: {e.text}")

    async def add_test_cases_comment(self, issue_key: str, test_cases: list[TestCase]) -> None:
        """Add test cases as a formatted comment on a Jira issue."""
        parts = ["h2. Generated Test Cases\n"]

        for tc in test_cases:
            parts.append(f"h3. {tc.id}: {tc.title}")
            parts.append(f"*Priority:* {tc.priority}")
            if tc.preconditions:
                parts.append(f"*Preconditions:* {tc.preconditions}")
            parts.append("*Steps:*")
            for i, step in enumerate(tc.steps, 1):
                parts.append(f"# {step}")
            parts.append(f"*Expected Result:* {tc.expected_result}")
            parts.append("")

        parts.append("----")
        parts.append("_Auto-generated by AI Release Tool_")

        try:
            self.client.add_comment(issue_key, "\n".join(parts))
            logger.info(f"Added test cases comment to {issue_key}")
        except JIRAError as e:
            logger.error(f"Jira comment error: {e.text}")
            raise RuntimeError(f"Failed to add comment to {issue_key}: {e.text}")

    async def add_release_notes_comment(self, issue_key: str, notes: ReleaseNote) -> None:
        """Add release notes as a comment on a Jira issue."""
        parts = ["h2. Release Notes\n"]
        if notes.summary:
            parts.append(f"*Summary:* {notes.summary}\n")

        if notes.features:
            parts.append("h3. New Features")
            for f in notes.features:
                parts.append(f"* {f}")
            parts.append("")

        if notes.bug_fixes:
            parts.append("h3. Bug Fixes")
            for f in notes.bug_fixes:
                parts.append(f"* {f}")
            parts.append("")

        if notes.breaking_changes:
            parts.append("h3. Breaking Changes")
            for c in notes.breaking_changes:
                parts.append(f"* (!) {c}")
            parts.append("")

        if notes.known_issues:
            parts.append("h3. Known Issues")
            for ki in notes.known_issues:
                parts.append(f"* {ki}")

        parts.append("\n----")
        parts.append("_Auto-generated by AI Release Tool_")

        try:
            self.client.add_comment(issue_key, "\n".join(parts))
            logger.info(f"Added release notes comment to {issue_key}")
        except JIRAError as e:
            logger.error(f"Jira comment error: {e.text}")
            raise RuntimeError(f"Failed to add release notes to {issue_key}: {e.text}")

    async def transition_issue(self, issue_key: str, transition_name: str) -> None:
        """Transition a Jira issue to a new status."""
        try:
            transitions = self.client.transitions(issue_key)
            target = next(
                (t for t in transitions if t["name"].lower() == transition_name.lower()),
                None,
            )
            if not target:
                available = [t["name"] for t in transitions]
                raise ValueError(
                    f"Transition '{transition_name}' not found. Available: {available}"
                )
            self.client.transition_issue(issue_key, target["id"])
            logger.info(f"Transitioned {issue_key} to '{transition_name}'")
        except JIRAError as e:
            logger.error(f"Jira transition error: {e.text}")
            raise RuntimeError(f"Failed to transition {issue_key}: {e.text}")

    async def get_project_info(self) -> dict:
        """Get project metadata for validation / UI display."""
        try:
            project = self.client.project(self.project_key)
            issue_types = [it.name for it in project.issueTypes]
            return {
                "key": project.key,
                "name": project.name,
                "issue_types": issue_types,
            }
        except JIRAError as e:
            logger.error(f"Jira project info error: {e.text}")
            raise RuntimeError(f"Failed to get project info: {e.text}")

    async def search_issues(self, query: str, max_results: int = 10) -> list[dict]:
        """Search Jira issues by JQL text search."""
        jql = f'project = {self.project_key} AND text ~ "{query}" ORDER BY created DESC'
        try:
            issues = self.client.search_issues(jql, maxResults=max_results)
            return [
                {
                    "key": issue.key,
                    "summary": issue.fields.summary,
                    "status": issue.fields.status.name,
                    "type": issue.fields.issuetype.name,
                    "url": f"{self.url}/browse/{issue.key}",
                }
                for issue in issues
            ]
        except JIRAError as e:
            logger.error(f"Jira search error: {e.text}")
            raise RuntimeError(f"Failed to search Jira: {e.text}")
